version: '3.9'
services:
  web:
    build: .
    container_name: table-top-web
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - HOST_CONSOLE_TOKEN=${HOST_CONSOLE_TOKEN}
      - SESSION_MAX_ROUNDS=${SESSION_MAX_ROUNDS}
      - ROUND_SECONDS=${ROUND_SECONDS}
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm i && npx prisma generate && (node socket-server.js &) && npm run dev"

  db:
    image: postgres:16-alpine
    container_name: table-top-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=table_top
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: table-top-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
